// Phase 153-01 — Append-only audit file for syncResource hook failures.
//
// Distinct from `_audit_stale.md` (fully regenerated by
// `scripts/kb-sync.cjs --audit-stale`; appending there would be silently
// wiped). This module writes to `.docflow-kb/_sync_failures.md` — a
// dedicated append-only log excluded from `validate-kb.cjs` via
// EXCLUDED_FILENAMES.
//
// Contract (KB-22):
//   - markStale(path, reason, details?) is fire-and-forget; it never throws.
//   - First call lazily writes a schema-valid frontmatter header
//     (type: audit, ttl: never, created_by: kb-audit, version 1.0.0).
//   - Subsequent calls append a single markdown-table row
//     (<200 bytes) via fs.appendFileSync — atomic on Linux for writes
//     below PIPE_BUF (4096).
//   - Error strings are sanitized: pipes replaced by U+2502, truncated
//     at 100 chars.
//
// Phase 153 Plans 02+03 call this from within try/catch blocks around
// `await syncResource(...)` on the failure path. The canonical audit
// record is the logger.error('kb-sync', ...) entry at the call site;
// this file is a secondary, user-facing reconciliation hint readable
// via `kb-sync.cjs --full-rebuild --source db`.
import * as fs from 'fs';
import * as path from 'path';

const DEFAULT_KB_ROOT = path.resolve(__dirname, '../../../../.docflow-kb');

function getKbRoot(): string {
  return process['env']['KB_ROOT'] || DEFAULT_KB_ROOT;
}

export interface StaleEntry {
  entity: string; // DB table name, e.g. 'cat_paws', 'catbrains', 'email_templates'
  db_id: string;
  error: string;
}

export type StaleReason =
  | 'create-sync-failed'
  | 'update-sync-failed'
  | 'delete-sync-failed'
  | 'markDeprecated-failed';

/**
 * Append a Phase 153 hook failure to `.docflow-kb/_sync_failures.md`.
 *
 * Never throws. First call lazily writes the frontmatter header.
 * Single-line entries (<200 bytes) are atomic per fs.appendFileSync on
 * Linux (PIPE_BUF 4096). Concurrent writes from the same process are
 * line-safe because appendFileSync on Linux uses O_APPEND semantics.
 *
 * @param kbRelPath  KB-relative path of the resource that failed to
 *                   sync (e.g. `resources/catpaws/abc-test.md`).
 * @param reason     Category of failure (see StaleReason union).
 * @param details    Optional {entity, db_id, error} triplet to populate
 *                   the row. Missing fields default to '?'.
 */
export function markStale(
  kbRelPath: string,
  reason: StaleReason,
  details?: StaleEntry,
): void {
  try {
    const kbRoot = getKbRoot();
    const filePath = path.join(kbRoot, '_sync_failures.md');

    if (!fs.existsSync(filePath)) {
      const iso = new Date().toISOString();
      const dateOnly = iso.slice(0, 10);
      const header = [
        '---',
        'id: sync-failures',
        'type: audit',
        'subtype: null',
        'lang: es',
        'title: Sync Failures Log',
        'summary: Append-only log of Phase 153 hook failures for reconciliation.',
        'tags: [ops]',
        'audience: [developer]',
        'status: active',
        `created_at: ${iso}`,
        'created_by: kb-audit',
        'version: 1.0.0',
        `updated_at: ${iso}`,
        'updated_by: kb-audit',
        'source_of_truth: null',
        'change_log:',
        `  - { version: 1.0.0, date: ${dateOnly}, author: kb-audit, change: Initial creation by markStale hook }`,
        'ttl: never',
        '---',
        '',
        '# Sync Failures Log',
        '',
        'Entries appended by Phase 153 hooks when `syncResource()` throws. Run',
        '`node scripts/kb-sync.cjs --full-rebuild --source db` to reconcile.',
        '',
        '| Timestamp | Reason | Entity | DB ID | KB Path | Error |',
        '|-----------|--------|--------|-------|---------|-------|',
        '',
      ].join('\n');
      fs.mkdirSync(path.dirname(filePath), { recursive: true });
      fs.writeFileSync(filePath, header);
    }

    const ts = new Date().toISOString();
    const errRaw = details?.error ?? '';
    // Pipes inside the error would break the markdown table. Replace with
    // the box-drawing vertical (U+2502) and truncate at 100 chars so the
    // row fits the <200-byte atomic-write budget even for common entity
    // name + id + timestamp payloads.
    const errTrunc = errRaw.replace(/\|/g, '\u2502').slice(0, 100);
    const line =
      `| ${ts} | ${reason} | ${details?.entity ?? '?'} | ${details?.db_id ?? '?'} | ${kbRelPath} | ${errTrunc} |\n`;
    fs.appendFileSync(filePath, line);
  } catch {
    // Last-ditch fallback: swallow. logger.error('kb-sync', ...) at the
    // call site is the canonical record; `_sync_failures.md` being
    // unwritable is not fatal to the Phase 153 hook's DB-wins guarantee.
  }
}
